# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#> .

`PerlX-ArraySkip-XS`
	:runtime-requirement    [ :on "perl 5.006000"^^:CpanId ];
	:configure-suggestion   [ :on "ExtUtils::Constant"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.47"^^:CpanId ].
